# Site settings
baseURL = "https://mom0tomo.github.io/"
languageCode = "ja"
title = "mom0tomo"
theme = "hugo-theme-cactus-plus"
canonifyurls = true
googleAnalytics = "$GA_ID"
hasCJKLanguage = true

[params]
	# Enter optionally your twitter account
	twitter = "mom0tomo"

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/mom0tomo/"
  twitter-square = "https://twitter.com/mom0tomo"
  github-square = "https://github.com/mom0tomo"
