# Site settings
title = "mom0tomo"
baseURL = "https://mom0tomo.github.io/"
languageCode = "ja"
theme = "hugo-theme-cactus-plus"
canonifyURLs = true
googleAnalytics = "UA-104531981-1"
hasCJKLanguage = true
buildDrafts = false
buildFuture = true
enableRSS = true

[social]
	facebook = "https://www.facebook.com/mom0tomo"
	twitter = "https://twitter.com/mom0tomo"
	github = "https://github.com/mom0tomo"

[params]
	name = "mom0tomo"
	description = "mom0tomo's Blog"
	bio = "Server-side Developer - Gopher"
	twitter = "mom0tomo"

	# Custom static files
	customCSS = ["css/custom.css"]
	customJS  = []

	# Google Analytics
	enableGoogleAnalytics = true

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	tags = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""

	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# "mono-social" or "font-awesome"
	iconFont = "mono-social"

	# The social icons can be styled differently if you use mono-social as font
	# circle, rounded, or empty
	socialIconStyle = "circle"

[blackfriday]
	hrefTargetBlank = true
