# Site settings
title = "mom0tomo"
baseURL = "https://mom0tomo.github.io/"
languageCode = "ja"
theme = "hugo-theme-cactus-plus"
# Google Analytics ID
googleAnalytics = "UA-104531981-1"
# use CJK統合漢字
hasCJKLanguage = true
# Include content with publishdate in the future.
buildFuture = true
# default = 10
paginate = 104

[social]
	facebook = "https://www.facebook.com/mom0tomo"
	twitter = "https://twitter.com/mom0tomo"
	github = "https://github.com/mom0tomo"

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
[markup]
  [markup.highlight]
  guessSyntax = true
	codeFences = true
	lineNoStart = 1
	lineNos = false
	lineNumbersInTable = true
	noClasses = true
	style = "monokai"
	tabWidth = 2

[params]
	name = "mom0tomo"
	description = "Thoughts and links about programming, by mom0tomo. I Love Go, Travel, Beer, Programming!"
	bio = "Server-side Developer - Gopher"
	twitter = "mom0tomo"
	images = ["avatar.png"]
	title = "mom0tomo.github.io"
	# Custom static files
	customCSS = ["css/custom.css"]
	customJS  = []
	# use Google Analytics
	enableGoogleAnalytics = true
	# Navigation links
	home = "Home"
	about = "About"
	archive = "Archives"
	subscribe = "Subscribe"
	tags = "Tag"
	rss = "rss"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# misc
	enableTwitterCard = true
	enableRSS = true
	# 404 page
	title404 = ""
	subtitle404 = ""
	# "mono-social" or "font-awesome"
	iconFont = "mono-social"
	# The social icons can be styled differently if you use mono-social as font
	# circle, rounded, or empty
	socialIconStyle = "circle"
