name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.7
        with: 
          hugo-version: '0.64.0'
        # Download (if necessary) and use Hugo extended version. Example: true
        # extended: # optional, default is false

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: mom0tomo/mom0tomo.github.io
          publish_branch: master
          publish_dir: ./public
          # personal_token: # optional 
          # publish_dir: # optional, default is public
          # If empty commits should be made to the publication branch
          # allow_empty_commit: # optional, default is false
          # If existing files in the publish branch should be not removed before deploying
          keep_files: true
          # Keep only the latest commit on a GitHub Pages branch
          # force_orphan: # optional, default is false
          # Set Git user.name
          # user_name: # optional
          # Set Git user.email
          # user_email: # optional
          # Set custom commit message
          # commit_message: # optional
          # Set tag name
          # tag_name: # optional
          # Set tag message
          # tag_message: # optional
